#!/bin/sh

set -o errexit
set -o pipefail
set -o nounset

python manage.py collectstatic --no-input
python manage.py migrate
python manage.py loaddata 01-defaults
python manage.py runserver_plus 0.0.0.0:8000
