# Generated by Django 2.0.3 on 2018-04-05 02:55

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('school_type', models.CharField(choices=[('B', 'Boarding'), ('C', 'Charter'), ('H', 'Homeschool'), ('LI', 'Language Immersion'), ('M', 'Magnet'), ('MO', 'Montessori'), ('O', 'Online'), ('PA', 'Parochial'), ('PS', 'Private Special Education'), ('PR', 'Private'), ('P', 'Public'), ('RE', 'Reggio Emilia'), ('R', 'Religious'), ('W', 'Waldorf')], db_column='type', default='P', max_length=2)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('address', models.ForeignKey(limit_choices_to={'location_type': 'S'}, on_delete=django.db.models.deletion.CASCADE, to='location.Location')),
            ],
            options={
                'verbose_name': 'School',
                'verbose_name_plural': 'Schools',
            },
        ),
    ]
