# Generated by Django 2.0.3 on 2018-04-02 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
        ('account', '0005_user_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.ManyToManyField(blank=True, limit_choices_to=models.Q(('location_type', 'H'), ('location_type', 'W'), _connector='OR'), to='location.Location'),
        ),
    ]
