# Generated by Django 2.0.3 on 2018-04-25 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_user_race_ethnicity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='locations',
            field=models.ManyToManyField(blank=True, limit_choices_to=models.Q(('location_type', 'H'), ('location_type', 'W'), _connector='OR'), to='location.Location'),
        ),
    ]
