# Generated by Django 2.0.3 on 2018-04-30 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_school'),
        ('account', '0010_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='schools',
            field=models.ManyToManyField(blank=True, to='location.School'),
        ),
    ]
