# Generated by Django 2.0.3 on 2018-05-30 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_user_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='medical_conditions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
