# Generated by Django 2.0.3 on 2018-04-09 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='location_type',
            new_name='type',
        ),
    ]
